"""
Extract all lines containing Chinese from the 3 files,
translate full lines using a comprehensive mapping,
then write back.
"""
import re, os

# Full line translations: (Chinese line content) -> (English line content)
# We match the Chinese portion within each line and replace it.

LINE_TRANSLATIONS = {
    # ==========================================
    # script_file.py - full sentence translations
    # ==========================================
    "竖屏": "portrait",
    "横屏": "landscape",
    "剪映": "JianYing",
    "花字效果": "text decoration effect",
    "花字": "text decoration",
    "气泡以及花字": "bubble and text decoration",
    "气泡和花字效果": "bubble and text decoration effect",
    "入场和": "intro and",
    "出场": "outro",
    "入场": "intro",
    "淡入淡出": "fade in/out",
    "音视频及": "audio/video and",
    "音视频": "audio/video",
    "音频效果": "audio effect",
    "音频": "audio",
    "视频帧率": "video frame rate",
    "视频的帧率": "video frame rate",
    "视频的总": "total video",
    "视频的": "video's",
    "视频": "video",
    "图片": "image",
    "图层": "layer",
    "图像调节": "image adjustment",
    "模板模式下": "in template mode",
    "模板而言应传入一个字符串列表": "template, a string list should be passed in",
    "模板模式": "template mode",
    "模板中替换": "replace in template",
    "模板": "template",
    "样式应用范围以尽量维持原有占比不变": "style application range to maintain original proportions as much as possible",
    "样式分布": "style distribution",
    "样式参考中的描边": "border in style reference",
    "样式参考中的": "in the style reference",
    "样式参考": "style reference",
    "样式": "style",
    "描边": "stroke/border",
    "绝对图层": "absolute layer",
    "渲染层级": "rendering layer order",
    "时间变化": "time change",
    "整体时间": "overall time",
    "时间": "time",
    "时间戳": "timestamp",
    "读取时间戳": "read timestamp",
    "单位为微秒": "unit is microseconds",
    "单位为像素": "unit is pixels",
    "微秒": "microseconds",
    "下标": "index",
    "越界": "out of bounds",
    "越高越接近前景": "higher is closer to foreground",
    "保持原有层级": "maintain original layer order",
    "按需修改渲染层级": "modify rendering layer order as needed",
    "和引用范围": "and reference range",
    "相对索引": "relative index",
    "相对": "relative",
    "内容替换": "content replacement",
    "内容写入": "content write to",
    "内容或本地": "content or local",
    "内容": "content",
    "固定宽高": "fixed width and height",
    "用于调整": "used to adjust",
    "大部分接口定义在此": "most interfaces are defined here",
    "字符串": "string",
    "正常": "normal",
    "暂不支持变速": "speed change not yet supported",
    "强度": "intensity",
    "能够调节强度": "can adjust intensity",
    "重叠": "overlap",
    "结构": "structure",
    "链接": "link",
    "输出": "output",
    "收集所有需要复制的": "collect all that need to be copied",
    "直接拷贝原始": "directly copy original",
    "直接将内容按行分割": "directly split content by lines",
    "复制其他可选属性": "copy other optional properties",
    "复制": "copy",
    "合并": "merge",
    "排序并": "sort and",
    "总长": "total length",
    "等长": "equal length",
    "为截断": "is truncated",
    "为全时段": "for the full duration",
    "为准": "as standard",
    "为否": "is false",
    "为最下层": "is the bottom layer",
    "为": "is/as",
    "值超出范围": "value out of range",
    "值": "value",
    "量": "amount",
    "方式": "method/way",
    "方法": "method",
    "主视频": "main video",
    "主": "main",
    "段替换内容": "segment replacement content",
    "段": "segment",
    "符合条件列表": "matching condition list",
    "列表中未提供或为": "not provided or is in the list",
    "列表中": "in the list",
    "列表": "list",
    "取值范围": "value range",
    "范围": "range",
    "尾部": "tail/end",
    "自动": "automatic",
    "应用": "apply",
    "长度与": "length and",
    "数量超过了该": "quantity exceeded the",
    "数量不匹配": "quantity mismatch",
    "数量": "quantity",
    "调整": "adjust",
    "仅当所选": "only when selected",
    "仅对视频": "only for video",
    "仅有一条时可省略": "can be omitted when there is only one",
    "仅在模板模式下有效": "only effective in template mode",
    "仅在模板模式下可用": "only available in template mode",
    "仅在": "only when",
    "不在模板模式下": "not in template mode",
    "不存在接受": "does not exist that accepts",
    "不存在名为": "does not exist with name",
    "不存在": "does not exist",
    "不修改样式参考中的": "do not modify in style reference",
    "不会使用参考": "will not use reference",
    "不指定则不根据下标筛选": "if not specified, no filtering by index",
    "不指定则不根据": "if not specified, no filtering by",
    "不匹配": "mismatch",
    "不正确": "incorrect",
    "不支持": "not supported",
    "不能与": "cannot be used with",
    "不": "not",
    "已存在同名": "already exists with same name",
    "已存在同": "already exists with same",
    "已存在": "already exists",
    "多次": "multiple times",
    "多个": "multiple",
    "包括普通": "including normal",
    "包含要": "contains to",
    "只有": "only",
    "只能有一个": "can only have one",
    "因而不支持向同一": "therefore does not support adding to the same",
    "以避免混淆": "to avoid confusion",
    "为避免混淆": "to avoid confusion",
    "以": "with/using",
    "如从模板": "such as from template",
    "如果指定了": "if specified",
    "如果指定则只": "if specified then only",
    "如果有气泡或花字效果": "if there is bubble or text decoration effect",
    "如果": "if",
    "如": "such as",
    "若提供则使用其样式": "if provided, use its style",
    "若已知": "if known",
    "若需要请显式为此函数传入": "if needed, explicitly pass to this function",
    "若不存在则自动": "if not exist then auto",
    "若是图片": "if it's an image",
    "寻找唯一的同": "search for the unique same",
    "查找": "find/search",
    "中查找接受该": "find one that accepts this in",
    "中查找": "find in",
    "中替换": "replace in",
    "未找到满足条件": "not found matching conditions",
    "未找到与新": "not found matching new",
    "未找到以下": "following not found",
    "未找到指定": "specified not found",
    "未提供样式参考时请提供": "please provide when style reference is not provided",
    "未找到": "not found",
    "没有找到名为": "not found with name",
    "没有找到满足条件": "not found matching conditions",
    "没有": "does not have",
    "存在多个接受": "multiple exist that accept",
    "找到多个名为": "found multiple with name",
    "找到多个满足条件": "found multiple matching conditions",
    "找到多个与新": "found multiple matching new",
    "尝试在": "try to in",
    "是否替换原": "whether to replace original",
    "是否重新计算": "whether to recalculate",
    "是否静音": "whether to mute",
    "是否存在于": "whether exists in",
    "否则会被剪映强制": "otherwise will be forced by JianYing",
    "时允许不指定": "allowed not to specify when",
    "时未提供": "not provided when",
    "长时": "longer",
    "短时的": "shorter",
    "长时的": "longer",
    "时的": "when",
    "时的样式": "style when",
    "时": "when",
    "当此": "when this",
    "当": "when",
    "会被": "will be",
    "会覆盖": "will override",
    "向指定的": "to the specified",
    "向指定": "to the specified",
    "向": "to/towards",
    "将直接覆盖相应": "will directly override the corresponding",
    "将按顺序逐个尝试直至": "will try one by one in order until",
    "将一个": "add one",
    "将": "will/convert",
    "使用源": "use source",
    "使": "make",
    "同类的": "of the same type",
    "同一": "same",
    "同": "same",
    "供有经验的用户使用": "for experienced users",
    "推荐使用": "recommended to use",
    "覆盖": "override",
    "某个": "a certain",
    "注意": "note",
    "顺序以枚举类成员的": "order follows enum member",
    "新的": "new",
    "新": "new",
    "与已有": "with existing",
    "与原": "with original",
    "与剪映中一致": "consistent with JianYing",
    "与": "with",
    "对于": "for",
    "对": "for/to",
    "则": "then",
    "或必须提供": "or must provide",
    "或视频": "or video",
    "或抛出异常": "or throw exception",
    "或": "or",
    "可通过": "can be accessed via",
    "可以是整数微秒值或时间字符串": "can be an integer microsecond value or time string",
    "可以自定义": "can be customized",
    "可能不在模板模式下": "may not be in template mode",
    "必须从": "must from",
    "必须与原": "must match original",
    "请指定": "please specify",
    "请为新": "please for new",
    "在所有": "in all",
    "在普通": "in normal",
    "在": "in",
    "到当前正在编辑的": "to the currently editing",
    "到当前": "to current",
    "到的": "found",
    "到": "to",
    "从原": "from original",
    "从": "from",
    "中的下标": "index in",
    "中的": "in the",
    "中": "in",
    "本方法会保留各": "this method will preserve each",
    "这种方法不会改变相应": "this method will not change the corresponding",
    "生成": "generate",
    "检查是否为本地": "check if local",
    "检查": "check",
    "总": "total",
    "维持原长不变": "maintain original length",
    "最底层的视频": "bottom layer video",
    "最后替换": "finally replace",
    "最后一个": "the last",
    "的所有": "all of",
    "的最上层": "the top layer of",
    "的渲染层级": "rendering layer order of",
    "的元数据": "metadata of",
    "的范围": "range of",
    "的": "of/the",
    "该": "this/the",
    "要替换的": "to be replaced",
    "要替换": "to replace",
    "要": "to/need",
    "超出": "exceeds",
    "指定的": "specified",
    "指定了": "specified",
    "指定不是": "specified is not",
    "指定": "specify",
    "提供的": "provided",
    "需要将它们": "need to convert them",
    "比原": "than original",
    "作为样式参考的": "as style reference",
    "作为样式参考": "as style reference",
    "支持传入一个": "supports passing in a",
    "支持普通": "supports normal",
    "及其": "and its",
    "属性": "property/attribute",
    "开启": "enable",
    "并影响所有引用它的": "and affects all that reference it",
    "并": "and",
    "而不是": "instead of",
    "即调整各": "i.e. adjust each",
    "一个剪映": "a JianYing",
    "一个指定": "a specified",
    "一个": "one/a",
    "目前只支持音视频和": "currently only supports audio/video and",
    "目前只支持视频和音频": "currently only supports video and audio",
    "尤其适合于图片": "especially suitable for images",
    "相关": "related",
    "且未指定": "and not specified",
    "以便在其上进行替换": "so that replacements can be made on it",
    "进行筛选": "to filter",
    "筛选": "filter",
    "有何": "what",
    "的项使用": "items use",
    "特定的": "specific",
    "但未找到对应": "but corresponding not found",
    "但提供了": "but provided",
    "但替换内容是": "but replacement content is",
    "转换为": "convert to",
    "上的视频": "video on",
    "上指定": "specify on",
    "上的": "on the",
    "上": "on",
    "加入": "add to",
    "根据指定": "based on specified",
    "开始时间": "start time",
    "持续时间": "duration",
    "除非指定为": "unless specified as",
    "不静音": "not muted",
    "由": "by",
    "有效": "valid/effective",
    "至打开时的": "to the time of opening",
    "至": "to",
    "出入场等": "intro/outro etc.",
    "第一个同": "the first same",
    "模仿剪映": "mimic JianYing",
    "替换指定音视频": "replace specified audio/video",
    "替换指定": "replace specified",
    "替换": "replace",
    "源": "source",
    "此": "this",
    "可选": "optional",
}

def translate_chinese_in_file(filepath):
    """Replace Chinese text in file using line-level matching."""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Sort by length descending so longer phrases match first
    sorted_items = sorted(LINE_TRANSLATIONS.items(), key=lambda x: len(x[0]), reverse=True)
    
    for cn, en in sorted_items:
        content = content.replace(cn, en)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    
    # Count remaining Chinese
    remaining = re.findall(r'[\u4e00-\u9fff]+', content)
    return remaining

base = os.path.dirname(os.path.abspath(__file__))
files = ['script_file.py', 'video_segment.py', 'template_mode.py']

for fname in files:
    fpath = os.path.join(base, fname)
    if not os.path.exists(fpath):
        print(f"SKIP: {fname} not found")
        continue
    remaining = translate_chinese_in_file(fpath)
    if remaining:
        unique = sorted(set(remaining), key=lambda x: -len(x))
        print(f"\n{fname}: {len(remaining)} occurrences, {len(unique)} unique phrases remaining:")
        for phrase in unique[:50]:
            print(f"  '{phrase}'")
    else:
        print(f"{fname}: ✓ All Chinese translated!")
