"""One-shot script to translate all Chinese comments/docstrings/error messages to English.
Run once, then delete this file."""

import re, os

# Translation dictionary: Chinese phrase -> English
TRANSLATIONS = {
    # === script_file.py ===
    "草稿文件中的素材信息部分": "Material information section of the draft file",
    "音频素材列表": "Audio material list",
    "视频素材列表": "Video material list",
    "贴纸素材列表": "Sticker material list",
    "文本素材列表": "Text material list",
    "音频特效列表": "Audio effect list",
    "音频淡入淡出效果列表": "Audio fade in/out effect list",
    "动画素材列表": "Animation material list",
    "视频特效列表": "Video effect list",
    "变速列表": "Speed change list",
    "蒙版列表": "Mask list",
    "转场效果列表": "Transition effect list",
    "滤镜/文本花字/文本气泡列表, 导出到`effects`中": "Filter/text decoration/text bubble list, exported to `effects`",
    "背景填充列表": "Background filling list",
    "根据IS_CAPCUT_ENV决定使用common_mask还是masks": "Decide whether to use common_mask or masks based on IS_CAPCUT_ENV",
    "草稿文件对象": "Draft file object",
    "草稿的宽度(像素)": "Draft width (pixels)",
    "草稿的高度(像素)": "Draft height (pixels)",
    "草稿中的所有轨道": "All tracks in the draft",
    "已导入的轨道列表": "List of imported tracks",
    "草稿中的所有素材": "All materials in the draft",
    "草稿的总时长(微秒)": "Total duration of the draft (microseconds)",
    "草稿文件": "Draft file",
    "草稿文件, 用于生成剪映/CapCut草稿": "Draft file, used to generate JianYing/CapCut drafts",
    "创建一个空的草稿文件": "Create an empty draft file",
    "视频宽度, 默认为1080": "Video width, default 1080",
    "视频高度, 默认为1920": "Video height, default 1920",
    "添加轨道": "Add track",
    "轨道类型": "Track type",
    "轨道名称, 若为None则使用默认名称": "Track name, if None use default name",
    "轨道名称, 若不为None则使用指定名称": "Track name, if not None use specified name",
    "同类轨道中的相对位置, 越大越靠前(越靠近观众)": "Relative position among tracks of the same type, higher value means closer to the viewer",
    "同类轨道中的相对位置, 越大越靠前": "Relative position among tracks of the same type, higher is more forward",
    "已存在同名轨道": "Track with the same name already exists",
    "根据类型和名称获取轨道": "Get track by type and name",
    "片段类型(如Video_segment), 用于确认轨道类型": "Segment type (e.g. Video_segment), used to determine track type",
    "轨道名称, 若为None则自动搜索唯一轨道": "Track name, if None then auto-search for the unique track",
    "轨道名称, 可选。若为None则自动搜索唯一轨道": "Track name, optional. If None then auto-search for the unique track",
    "找不到对应的轨道": "Cannot find the corresponding track",
    "存在多条同类轨道时必须指定轨道名称": "Must specify track name when multiple tracks of the same type exist",
    "找不到名为": "Cannot find track named",
    "的轨道": "",
    "获取已导入的轨道": "Get imported track",
    "要搜索的轨道类型": "Track type to search for",
    "要搜索的轨道名称": "Track name to search for",
    "向指定轨道添加一个片段": "Add a segment to the specified track",
    "要添加的片段对象": "Segment object to add",
    "轨道名称, 可选": "Track name, optional",
    "向指定轨道添加一个片段, 自动处理素材和时间范围": "Add a segment to the specified track, automatically handle materials and time ranges",
    "添加片段到轨道": "Add segment to track",
    "添加一个特效到轨道": "Add an effect to the track",
    "特效类型": "Effect type",
    "时间范围": "Time range",
    "参数列表, 其中未给出或为None的项使用默认值": "Parameter list, items not provided or None use default values",
    "添加特效": "Add effect",
    "轨道名称": "Track name",
    "获取轨道上的最后一个片段": "Get the last segment on the track",
    "获取最后一个片段": "Get last segment",
    "导出草稿文件": "Export draft file",
    "导出路径, 若为None则返回字符串": "Export path, if None return string",
    "导出到文件": "Export to file",
    "将草稿内容导出到文件": "Export draft content to file",
    "输出文件路径": "Output file path",
    "将草稿内容导出为字符串": "Export draft content as string",
    "返回草稿内容的JSON字符串": "Return JSON string of draft content",
    "从JSON文件中导入草稿": "Import draft from JSON file",
    "JSON文件路径": "JSON file path",
    "导入SRT字幕": "Import SRT subtitles",
    "SRT内容字符串": "SRT content string",
    "文字样式": "Text style",
    "字体类型": "Font type",
    "裁剪/位置设置": "Clip/position settings",
    "样式参考(若提供则覆盖text_style和font)": "Style reference (overrides text_style and font if provided)",
    "边框样式": "Border style",
    "背景样式": "Background style",
    "时间偏移量(微秒)": "Time offset (microseconds)",
    "气泡效果": "Bubble effect",
    "文本特效": "Text effect",
    "解析SRT字幕文件": "Parse SRT subtitle file",
    "解析SRT内容": "Parse SRT content",
    "不是有效的SRT格式": "is not a valid SRT format",
    "时间格式解析失败": "Time format parsing failed",
    "添加文本轨道": "Add text track",
    "已存在名为": "Already exists track named",
    "的文本轨道": "text track",
    "创建文字片段": "Create text segment",
    "添加文字片段到轨道": "Add text segment to track",
    "获取指定轨道": "Get specified track",
    "获取轨道": "Get track",
    "主轨道": "Main track",
    "素材": "Material",
    "片段": "Segment",
    "轨道": "Track",
    "时长": "Duration",
    "宽度": "Width",
    "高度": "Height",
    "类型": "Type",
    "名称": "Name",
    "路径": "Path",
    "速度": "Speed",
    "音量": "Volume",
    "位置": "Position",
    "缩放": "Scale",
    "旋转": "Rotation",
    "透明度": "Opacity",
    "动画": "Animation",
    "特效": "Effect",
    "滤镜": "Filter",
    "蒙版": "Mask",
    "转场": "Transition",
    "关键帧": "Keyframe",
    "字幕": "Subtitle",
    "文本": "Text",
    "文字": "Text",
    "背景": "Background",
    "边框": "Border",
    "阴影": "Shadow",
    "颜色": "Color",
    "字体": "Font",
    "大小": "Size",
    "粗体": "Bold",
    "斜体": "Italic",
    "下划线": "Underline",
    "对齐": "Alignment",
    "垂直": "Vertical",
    "水平": "Horizontal",
    "偏移": "Offset",
    "圆角": "Round corner",
    "模糊": "Blur",
    "羽化": "Feather",
    "反转": "Invert",
    "裁剪": "Crop",
    "填充": "Fill",
    "入场动画": "Intro animation",
    "出场动画": "Outro animation",
    "循环动画": "Loop animation",
    "组合动画": "Combo animation",
    "贴纸": "Sticker",
    "草稿": "Draft",
    "导出": "Export",
    "导入": "Import",
    "保存": "Save",
    "加载": "Load",
    "缓存": "Cache",
    "下载": "Download",
    "上传": "Upload",
    "处理": "Process",
    "创建": "Create",
    "删除": "Delete",
    "更新": "Update",
    "查询": "Query",
    "获取": "Get",
    "设置": "Set",
    "添加": "Add",
    "移除": "Remove",
    "默认": "Default",
    "参数": "Parameter",
    "返回": "Return",
    "错误": "Error",
    "警告": "Warning",
    "失败": "Failed",
    "成功": "Success",
    "开始": "Start",
    "结束": "End",
    "完成": "Complete",
    "进度": "Progress",
    "状态": "Status",
    "信息": "Info",
    "配置": "Config",
    "环境": "Environment",
    "版本": "Version",
    "资源": "Resource",
    "文件": "File",
    "目录": "Directory",
    "压缩": "Compress",
    "解压": "Extract",
    "临时": "Temporary",
    "清理": "Clean up",

    # === video_segment.py ===
    "视频/图片片段": "Video/image segment",
    "视频片段对象, 同时用于处理图片": "Video segment object, also used for handling images",
    "视频素材对象": "Video material object",
    "目标时间范围(在轨道上的位置和时长)": "Target time range (position and duration on the track)",
    "截取的素材片段的时间范围, 默认从开头根据`speed`截取与`target_timerange`等长的一部分": "Source clip time range, by default clips from the beginning based on `speed` to match `target_timerange` duration",
    "播放速度": "Playback speed",
    "裁剪和位置设置": "Crop and position settings",
    "音量, 1.0为原始音量": "Volume, 1.0 is original volume",
    "添加动画效果": "Add animation effect",
    "动画类型": "Animation type",
    "动画时长(微秒)": "Animation duration (microseconds)",
    "添加场景特效或人物特效": "Add scene effect or character effect",
    "时长(微秒), 不指定则与片段等长": "Duration (microseconds), if not specified same as segment duration",
    "参数列表, 其中未给出或为None的项使用默认值。注意列表是从后往前匹配各参数的": "Parameter list, items not provided or None use default values. Note the list matches parameters from back to front",
    "不支持的特效类型": "Unsupported effect type",
    "添加滤镜": "Add filter",
    "滤镜类型": "Filter type",
    "滤镜强度, 默认为100(最大值)": "Filter intensity, default 100 (maximum)",
    "获取草稿的宽高，而不是使用素材的宽高": "Get draft width/height instead of using material width/height",
    "添加蒙版": "Add mask",
    "蒙版类型, 从Mask_type枚举中选择": "Mask type, choose from Mask_type enum",
    "蒙版中心横坐标(素材像素)": "Mask center X coordinate (material pixels)",
    "蒙版中心横坐标(素材像素), 默认设置在素材中心": "Mask center X coordinate (material pixels), default set at material center",
    "蒙版中心纵坐标(素材像素), 默认设置在素材中心": "Mask center Y coordinate (material pixels), default set at material center",
    "蒙版主尺寸, 以素材高度的比例表示, 默认为0.5": "Mask main size, as a ratio of material height, default 0.5",
    "蒙版顺时针旋转角度, 默认不旋转": "Mask clockwise rotation angle, default no rotation",
    "蒙版羽化参数, 范围0~100, 默认不羽化": "Mask feather parameter, range 0-100, default no feather",
    "是否反转蒙版, 默认不反转": "Whether to invert mask, default not inverted",
    "矩形蒙版宽度, 仅在蒙版类型为矩形时允许, 以素材宽度的比例表示": "Rectangle mask width, only allowed when mask type is rectangle, as a ratio of material width",
    "矩形蒙版圆角参数, 仅在蒙版类型为矩形时允许, 范围0~100": "Rectangle mask round corner parameter, only allowed when mask type is rectangle, range 0-100",
    "只有矩形蒙版才能设置宽度": "Only rectangle mask can set width",
    "只有矩形蒙版才能设置圆角": "Only rectangle mask can set round corner",
    "添加转场效果": "Add transition effect",
    "转场类型, 从Transition_type枚举中选择": "Transition type, choose from Transition_type enum",
    "转场时长(微秒), 不指定则使用转场类型的默认时长": "Transition duration (microseconds), if not specified use transition type default duration",
    "不支持的转场类型": "Unsupported transition type",
    "背景填充": "Background filling",
    "添加背景填充效果": "Add background filling effect",
    "填充类型, 可选": "Filling type, options:",
    "原始, 即不做任何填充": "Original, no filling",
    "模糊填充": "Blur filling",
    "颜色填充": "Color filling",
    "图片填充": "Image filling",
    "模糊程度, 仅在`fill_type`为": "Blur level, only when `fill_type` is",
    "模糊程度, 范围0.0~1.0": "Blur level, range 0.0-1.0",
    "背景颜色, 仅在`fill_type`为": "Background color, only when `fill_type` is",
    "时有效": "is effective",
    "背景颜色, 格式为'#RRGGBBAA'": "Background color, format '#RRGGBBAA'",
    "不支持的填充类型": "Unsupported fill type",
    "贴纸片段": "Sticker segment",
    "贴纸片段对象": "Sticker segment object",
    "贴纸资源ID": "Sticker resource ID",
    "贴纸的时间范围": "Sticker time range",
    "贴纸的位置和大小设置": "Sticker position and size settings",
    "导出素材信息": "Export material information",
    "导出贴纸素材信息": "Export sticker material information",
    "request_id字段": "request_id fields",

    # === template_mode.py ===
    "与模板模式相关的类及函数等": "Classes and functions related to template mode",
    "处理替换素材时素材变短情况的方法": "Methods for handling shorter replacement material",
    "裁剪头部, 即后移片段起始点": "Trim head, move segment start point forward",
    "裁剪尾部, 即前移片段终止点": "Trim tail, move segment end point backward",
    "裁剪尾部并消除间隙, 即前移片段终止点, 后续片段也依次前移": "Trim tail and eliminate gaps, move segment end point backward, subsequent segments shift forward accordingly",
    "保持中间点不变, 两端点向中间靠拢": "Keep midpoint unchanged, both endpoints move toward center",
    "处理替换素材时素材变长情况的方法": "Methods for handling longer replacement material",
    "裁剪素材尾部(覆盖`source_timerange`参数), 使得片段维持原长不变, 此方法总是成功": "Trim material tail (overrides `source_timerange`), keeping segment at original length, this method always succeeds",
    "减速播放(覆盖`speed`参数), 使得片段维持原长不变, 此方法总是成功": "Slow down playback (overrides `speed`), keeping segment at original length, this method always succeeds",
    "模板模式下的可替换片段": "Replaceable segment in template mode",
    "可替换的片段, 这是一个轻量封装": "Replaceable segment, this is a lightweight wrapper",
    "原始片段对象": "Original segment object",
    "片段所在轨道": "Track containing the segment",
    "素材变短时的处理方法": "Method for handling shorter material",
    "素材变长时的处理方法": "Method for handling longer material",
    "是否可替换": "Whether it is replaceable",
    "将此片段标记为可替换": "Mark this segment as replaceable",
    "替换此片段的素材": "Replace this segment's material",
    "新的素材对象": "New material object",
    "新素材时长(微秒), 若不提供则不改变时间范围": "New material duration (microseconds), if not provided time range won't change",
    "新素材时长不能为0": "New material duration cannot be 0",
    "新素材比原素材短, 采取策略": "New material is shorter than original, adopting strategy",
    "新素材比原素材长, 采取策略": "New material is longer than original, adopting strategy",
    "模板模式上下文": "Template mode context",
    "模板模式的上下文管理器": "Template mode context manager",
    "进入模板模式时, 设置模板标识": "When entering template mode, set template flag",
    "退出模板模式时, 清除模板标识并更新时长": "When exiting template mode, clear template flag and update duration",
    "获取指定轨道上的可替换片段列表": "Get list of replaceable segments on the specified track",
    "片段类型(如Video_segment)": "Segment type (e.g. Video_segment)",
    "轨道名称, 默认为None自动搜索唯一轨道": "Track name, default None to auto-search for unique track",
    "返回可替换片段列表": "Returns list of replaceable segments",
    "该轨道上没有片段": "No segments on this track",
    "在指定位置将轨道上的片段分割为两段": "Split a segment on the track at the specified position",
    "轨道上片段的索引(从0开始)": "Segment index on the track (0-based)",
    "分割位置(微秒), 相对于片段的target_timerange.start": "Split position (microseconds), relative to segment's target_timerange.start",
    "分割后的两个片段": "The two segments after splitting",
    "片段索引超出范围": "Segment index out of range",
    "分割位置必须在片段内部": "Split position must be inside the segment",
    "不支持的片段类型": "Unsupported segment type",
}

def translate_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Sort by length descending to replace longer phrases first
    sorted_items = sorted(TRANSLATIONS.items(), key=lambda x: len(x[0]), reverse=True)
    
    for cn, en in sorted_items:
        content = content.replace(cn, en)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    
    # Check remaining Chinese
    remaining = re.findall(r'[\u4e00-\u9fff]+', content)
    return remaining

base = os.path.dirname(os.path.abspath(__file__))
files = ['script_file.py', 'video_segment.py', 'template_mode.py']

for fname in files:
    fpath = os.path.join(base, fname)
    remaining = translate_file(fpath)
    if remaining:
        print(f"{fname}: {len(remaining)} remaining Chinese phrases:")
        for phrase in set(remaining):
            print(f"  - {phrase}")
    else:
        print(f"{fname}: All Chinese translated!")
