param(
    [string]$OutputDir = "samples/render-benchmark-2min",
    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Resolve-FFmpeg {
    $cmd = Get-Command ffmpeg -ErrorAction SilentlyContinue
    if ($null -eq $cmd) {
        throw "ffmpeg was not found in PATH. Install FFmpeg or add it to PATH."
    }

    return $cmd.Source
}

$ffmpeg = Resolve-FFmpeg
$root = Resolve-Path (Join-Path $PSScriptRoot "..")
$target = Join-Path $root $OutputDir

if (Test-Path $target) {
    if (-not $Force) {
        throw "Target folder already exists: $target. Use -Force to overwrite."
    }

    Remove-Item -Recurse -Force $target
}

New-Item -ItemType Directory -Path $target | Out-Null

Write-Host "Generating 2-minute benchmark sample in: $target"

$audioPath = Join-Path $target "audio_main_120s.wav"
$bgMainPath = Join-Path $target "bg_main_1080x1920.png"
$bgAltPath = Join-Path $target "bg_alt_1080x1920.png"
$overlayPath = Join-Path $target "overlay_frame_1080x1920.png"
$brollPath = Join-Path $target "broll_testsrc_12s.mp4"

# Audio: two-tone mix with fades, long enough for a 2-minute timeline.
& $ffmpeg -y `
    -f lavfi -i "sine=frequency=220:sample_rate=48000:duration=120" `
    -f lavfi -i "sine=frequency=440:sample_rate=48000:duration=120" `
    -filter_complex "[0:a]volume=0.55[a0];[1:a]volume=0.20[a1];[a0][a1]amix=inputs=2:normalize=0,afade=t=in:st=0:d=1,afade=t=out:st=118:d=2" `
    -c:a pcm_s16le $audioPath | Out-Null

# Main portrait background.
& $ffmpeg -y `
    -f lavfi -i "color=c=#1B2A41:s=1080x1920:d=1,format=rgba,drawbox=x=0:y=0:w=1080:h=640:color=#324A5F@0.80:t=fill,drawbox=x=0:y=640:w=1080:h=640:color=#4C6A92@0.80:t=fill,drawbox=x=0:y=1280:w=1080:h=640:color=#86A5D9@0.80:t=fill" `
    -frames:v 1 $bgMainPath | Out-Null

# Alternate portrait background.
& $ffmpeg -y `
    -f lavfi -i "color=c=#101820:s=1080x1920:d=1,format=rgba,drawbox=x=80:y=180:w=920:h=1560:color=#F2AA4C@0.20:t=fill,drawbox=x=120:y=220:w=840:h=1480:color=#FFFFFF@0.08:t=fill" `
    -frames:v 1 $bgAltPath | Out-Null

# Transparent overlay frame for branding/visual depth.
& $ffmpeg -y `
    -f lavfi -i "color=c=black@0.0:s=1080x1920:d=1,format=rgba,drawbox=x=20:y=20:w=1040:h=1880:color=#FFFFFF@0.30:t=8,drawbox=x=40:y=40:w=1000:h=80:color=#F2AA4C@0.45:t=fill" `
    -frames:v 1 $overlayPath | Out-Null

# Short b-roll clip for mixed image/video timelines.
& $ffmpeg -y `
    -f lavfi -i "testsrc2=s=1080x1920:r=30:d=12" `
    -f lavfi -i "sine=frequency=330:sample_rate=48000:duration=12" `
    -shortest `
    -c:v libx264 -pix_fmt yuv420p -preset veryfast `
    -c:a aac -b:a 160k `
    $brollPath | Out-Null

$readmePath = Join-Path $target "README.md"
@"
# 2-Minute Render Benchmark Sample

Generated by `scripts/Generate-RenderSample2Min.ps1`.

## Files
- `audio_main_120s.wav`: main audio bed (120 seconds)
- `bg_main_1080x1920.png`: primary portrait background
- `bg_alt_1080x1920.png`: alternate portrait background
- `overlay_frame_1080x1920.png`: transparent overlay frame
- `broll_testsrc_12s.mp4`: short vertical test video

## Quick timeline setup suggestion (in app)
1. Add `audio_main_120s.wav` as primary audio.
2. Add 12 visual segments x 10s each, alternating between `bg_main_1080x1920.png` and `bg_alt_1080x1920.png`.
3. Add `overlay_frame_1080x1920.png` across the full 120s on top layer.
4. Replace one of the 10s blocks with `broll_testsrc_12s.mp4` to test mixed media handling.

This gives a repeatable, lightweight 2-minute project for render comparison.
"@ | Set-Content -Path $readmePath -Encoding UTF8

Write-Host "Done. Sample created at: $target"
