// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PodcastVideoEditor.Core.Database;

#nullable disable

namespace PodcastVideoEditor.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328100000_AddOverlayProperties")]
    partial class AddOverlayProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");
            // Intentionally minimal — full model is in AppDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
