// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PodcastVideoEditor.Core.Database;

#nullable disable

namespace PodcastVideoEditor.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318100000_AddKeywordsToSegment")]
    partial class AddKeywordsToSegment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("PodcastVideoEditor.Core.Models.Segment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundAssetId")
                        .HasColumnType("TEXT");

                    b.Property<double>("EndTime")
                        .HasColumnType("REAL");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Keywords")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("StartTime")
                        .HasColumnType("REAL");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackId")
                        .HasColumnType("TEXT");

                    b.Property<double>("TransitionDuration")
                        .HasColumnType("REAL");

                    b.Property<string>("TransitionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Volume")
                        .HasColumnType("REAL");

                    b.Property<double>("FadeInDuration")
                        .HasColumnType("REAL");

                    b.Property<double>("FadeOutDuration")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_Segment_ProjectId");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("IX_Segment_TrackId");

                    b.ToTable("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
