// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PodcastVideoEditor.Core.Database;

#nullable disable

namespace PodcastVideoEditor.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320100000_AddSegmentSourceStartOffset")]
    partial class AddSegmentSourceStartOffset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("PodcastVideoEditor.Core.Models.Segment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("SourceStartOffset")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
