// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PodcastVideoEditor.Core.Database;

#nullable disable

namespace PodcastVideoEditor.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326100000_AddMotionEffectProperties")]
    partial class AddMotionEffectProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("PodcastVideoEditor.Core.Models.Segment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotionPreset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("MotionIntensity")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Segments");
                });

            modelBuilder.Entity("PodcastVideoEditor.Core.Models.Track", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoMotionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MotionIntensity")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
